EJERCICIO 1
Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. 
Sobre el array creado anteriormente, extraed: 

In [22]:
import numpy as np

In [23]:
np.random.seed(5)
array1 = np.random.rand(2,3,5)
array1 

array([[[0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119],
        [0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123],
        [0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703]],

       [[0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.57983781],
        [0.5999292 , 0.26581912, 0.28468588, 0.25358821, 0.32756395],
        [0.1441643 , 0.16561286, 0.96393053, 0.96022672, 0.18841466]]])

In [24]:
array1=np.round(array1,1)
array1

array([[[0.2, 0.9, 0.2, 0.9, 0.5],
        [0.6, 0.8, 0.5, 0.3, 0.2],
        [0.1, 0.7, 0.4, 0.2, 0.9]],

       [[0.3, 0.4, 0.3, 0.6, 0.6],
        [0.6, 0.3, 0.3, 0.3, 0.3],
        [0.1, 0.2, 1. , 1. , 0.2]]])

EJERCICIO 2 Calculad la media del array y almacenarlos en una variable. Redondead a un decimal. 

In [12]:
media=round(np.mean(array1),1)
media

0.5

EJERCICIO 3 Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal. 

In [13]:
maximo=round(np.max(array1),1)
maximo

1.0

EJERCICIO 4
Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal. 

In [14]:
minimo=round(np.min(array1),1)
minimo

0.1

EJERCICIO 5

Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
Si el valor del array es igual que la media, se reemplaza por "A".
Si el valor del array es mayor que la media, se reemplaza por "B".
Si el valor del array es menor que la media, se reemplaza por "C".
Si el valor es igual que el máximo, se reemplaza por "D".
Si el valor es igual que el mínimo, se reemplaza por "E". 


In [15]:
array_v=np.empty_like(array1)
array_v

array([[[0.2, 0.9, 0.2, 0.9, 0.5],
        [0.6, 0.8, 0.5, 0.3, 0.2],
        [0.1, 0.7, 0.4, 0.2, 0.9]],

       [[0.3, 0.4, 0.3, 0.6, 0.6],
        [0.6, 0.3, 0.3, 0.3, 0.3],
        [0.1, 0.2, 1. , 1. , 0.2]]])

In [27]:
for x in array_v:
    for y in x :
        for z in y:
                        
            if z== media:
                z="A"
                
            elif z> media:
                z="B"
                
            elif z< media:
                z="C"
                
            elif z== maximo:
                z="D"
                
            elif z== minimo:
                z="E"
                
print(array_v)

[[[0.2 0.9 0.2 0.9 0.5]
  [0.6 0.8 0.5 0.3 0.2]
  [0.1 0.7 0.4 0.2 0.9]]

 [[0.3 0.4 0.3 0.6 0.6]
  [0.6 0.3 0.3 0.3 0.3]
  [0.1 0.2 1.  1.  0.2]]]
